const types = {
    GET_DISRUPTIONS: 'GET_DISRUPTIONS',
    SET_DISRUPTIONS: 'SET_DISRUPTIONS',
    DISRUPTIONS_ERROR: 'DISRUPTIONS_ERROR',

    GET_STATIONS: 'GET_STATIONS',
    SET_STATIONS: 'SET_STATIONS',
    STATIONS_ERROR: 'STATIONS_ERROR',

    SET_SERVICE_STATUS: 'SET_SERVICE_STATUS',

    GET_LOCATION: 'GET_LOCATION',
};

export default types;
