const types = {
    GET_DISRUPTIONS: 'GET_DISRUPTIONS',
    SET_DISRUPTIONS: 'SET_DISRUPTIONS',
    DISRUPTIONS_ERROR: 'DISRUPTIONS_ERROR',

    SET_SERVICE_STATUS: 'SET_SERVICE_STATUS',

    GET_LOCATION: 'GET_LOCATION',
};

export default types;
